### ISSUE TITLE
Too hard.

### ISSUE THREAD

**Issue by Michael2-3B** [Legend-of-iPhoenix/Mys#2]
Mys is way too hard.

I've only learned about 5 of the characters that actually do anything, and iPhoenix has failed to give me any more hints even after trying to bribe him. Needless to say, I'm stuck. I've literally tried every character to see what they do.

Please give more hints.

**Comment by Legend-of-iPhoenix** [comment]
I'm sorry to hear that you are experiencing difficulties with Mys.

I sent you a decently large hint the other day, I hope it helps.

I'm considering adding challenges that are easier so that people that are just gaining a foothold can do better.

Once we get enough challenges, I might limit the number of challenges each user can get credit for.

[By the way, you can now suggest challenges :)](https://goo.gl/forms/uvFgHytkwrZJMkV03)
